### PR TITLE
Solution: Fix warnings

### PR DESCRIPTION
**Pull request by c-rack**
1. Unused variable `reason`
2. Unused function `mask_by_ip/1`

### CODE REVIEW

**Comment by duijf** [comment]
I don't have a particular preference for one or the other, so I'm asking. Why did you go for the erlang atom instead of an error string?

**Comment by c-rack** [comment]
It is what we get back from `:inet.parse_address`. Otherwise, we would match against `{:error, _reason}` and override the reason, which may hide information.

**Comment by c-rack** [comment]
And by the way, please merge first and discuss later. :-)
This video explains the reasons very well:
http://www.youtube.com/watch?v=O8CbzKREAj4
_(maybe you hear a familiar name around minute 19)_

**Comment by duijf** [comment]
Alright! Okay by me

**Pull request merged**
