### PR TITLE
Update version, add @duijf as maintainer

### PR DESCRIPTION
**Pull request by c-rack**

### CODE REVIEW

**Comment by duijf** [comment]
This might need to sit for a bit before I've had a chance to update the docs in accordance with my changes. Working on that now.

**Comment by duijf** [comment]
Now a work in progress: #4

**Comment by c-rack** [comment]
OK, we can wait for #4, but normally, we should merge all PRs as soon as possible if they are "correct":

> Maintainers SHALL merge correct patches from other Contributors rapidly

http://rfc.zeromq.org/spec:22

;-)

**Comment by duijf** [comment]
Alright, I've cut the scope of that PR and am merging this :)

**Pull request merged**
